package movie

import "go.mongodb.org/mongo-driver/bson/primitive"

type Netflix struct {
	/*
			If Id is not deined in the struct it will be generated by MongoDB
		But will not be accessible as an object in the struct
	*/
	ID        primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	Name      string             `json:"movieName,omitempty" bson:"movieName"`
	IsWatched bool               `json:"isWatched" bson:"isWatched"`
	Star      Star               `bson:"inline"` // inline will flatten the object to the root level
	// e.g gor Inline movie { movieName, isWatched , (star will be replacedwith) starName, starAge }
}

type Star struct {
	Name string `json:"starName,omitempty" bson:"starName"`
	Age  uint16 `json:"starAge,omitempty" bson:"starAge"`
}
